config/routes.rb
Livrodaclasse::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  match 'scraps/:id/new', :to => 'scraps#new', :as => :new_scrap


  get 'entrar', :to => 'sessions#new', :as => :signin
  get 'auth/:provider/callback', :to => 'sessions#create'
  delete 'sair', :to => 'sessions#destroy', :as => :signout
  get 'cadastro', :to => 'users#new', :as => :new_user
  get 'apphome', :to => 'books#index', :as => :app_home
  get 'auth/failure', :to => redirect('/')
  get 'projects/terms_of_service', :to => 'projects#terms_of_service', :as => :terms_of_service
  match 'texts/enable_or_disable', :to => 'texts#enable_or_disable', :as => :enable_or_disable
  root :to => 'pages#home'
  get 'manual', :to => 'pages#manual'

  match 'contact' => 'pages#contact', :via => :post

  resources :users do
    collection do
      get 'email'
    end
  end

  resources :sessions
  resources :password_resets
  resources :books do

    member do
      post 'rules/active', to: 'books#rule_active'
    end

    resources :texts do
      post 'cancel'
      collection do
        get 'all'
        put 'save_all'
      end

      resources :comments
      collection do
        post 'sort'
      end
    end
    resources :collaborators do
      member do
        get 'resend_invitation'
      end
    end
    resources :projects
    resources :scraps
  end
  get 'books/:id/cover_info', to: 'books#cover_info', as: :book_cover_info
  get 'books/:id/revision', to: 'books#revision', as: :book_revision
  get 'books/:id/epub_viewer', to: 'books#epub_viewer', as: :epub_viewer
  post 'books/:id/upload_text', to: 'texts#create', as: :upload_text
  match 'books/:id/update_cover_info', to: 'books#update_cover_info', as: :book_update_cover_info
  match 'books/:id/generate_cover', to: 'books#generate_cover', as: :book_generate_cover

  match 'books/:id/generate_pdf', to: 'books#generate_pdf', as: :book_generate_pdf
  match 'books/:id/ask_for_download_pdf', to: 'books#ask_for_download_pdf', as: :book_ask_for_download_pdf
  match 'books/:id/download_pdf', to: 'books#download_pdf', as: :book_download_pdf
  match 'books/:id/generate_ebook', to: 'books#generate_ebook', as: :book_generate_ebook

  match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
  match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer
  resources :scraps, :only => [:index, :create, :edit, :update, :destroy]

  namespace :admin do
    root :to => 'dashboard#index'

    match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
    match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer

    match 'users/:id/books', :to => 'users#books', :as => :users_books
    match 'users/add_book', :to => 'users#add_book', :as => :users_add_book
    match 'users/remove_book', :to => 'users#remove_book', :as => :users_remove_book

    get 'dashboard/default_cover', :to => 'dashboard#default_cover', :as => :default_cover
    match 'dashboard/update_default_cover', :to => 'dashboard#update_default_cover', :as => :update_default_cover

    match 'dashboard/revision', :to => 'dashboard#revision', :as => :revision
    match 'dashboard/manual', :to => 'dashboard#manual', :as => :manual
    post 'dashboard/manual/update', :to => 'dashboard#manual_update', :as => :manual_update

    match 'projects/refresh', :to => 'projects#refresh', :as => :projects_refresh

    match 'projects/push', :to => 'projects#push', :as => :projects_push

    resources :projects, :only => [:index, :show, :edit, :update] do
      member do
        get 'impersonate'
        get 'refresh'
        get 'push'
      end
    end
    resources :templates, :only => :index
    resources :expressions, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :book_statuses, :only => [:index, :create, :new, :edit, :update]
    resources :profiles, :only => [:index, :create, :new, :edit, :update]
    resources :permissions, :only => [:index, :edit, :update]
    resources :publishers, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :scraps, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :users, :only => [:index, :edit, :update, :new, :create]
    resources :rules, :only => [:index, :new, :create, :destroy, :edit, :update] do
      collection do
        post 'active'
      end
    end
  end
  get '/:locale' => 'pages#home'
end

app/models/rule.rb
# Rule Model
class Rule < ActiveRecord::Base
  attr_accessible :label, :command
  has_and_belongs_to_many :books

  validates                 :label,     presence: true, length: { maximum: 30 }
  validates                 :command,   presence: true
end

app/controllers/admin/rules_controller.rb
module Admin
  # Rule Controller
  class RulesController < Admin::ApplicationController

    def index
      @rules = Rule.all
    end

    def new
      @rule = Rule.new
    end

    def destroy
      @rule = Rule.find(params[:id])
      @rule.destroy
      redirect_to admin_rules_path, notice: 'Rotina removida com sucesso.'
    end

    def create
      @rule = Rule.new(params[:rule])
      if @rule.save
        redirect_to admin_rules_path, notice: 'Uma nova rotina foi definida.'
      else
        render :new
      end
    end

    def edit
      @rule = Rule.find(params[:id])
    end

    def update
      @rule = Rule.find(params[:id])
      @rule.update_attributes(params[:rule])
      if @rule.save
        redirect_to admin_rules_path, notice: 'Rotina atualizada.'
      else
        render :edit
      end
    end

    def active
      rule = Rule.find(params[:id])
      active = rule.active
      rule.active = !active
      if rule.save
        render json: { result: 'success' }
      else
        render json: { result: 'fail' }
      end
    end
  end
end

app/views/admin/rules/_form.html.erb
<%= simple_form_for([:admin, @rule], :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :label, labe: 'Label:' %>
    <%= f.input :command, as: :text, label: 'Comando:'%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/rules/edit.html.erb
<h3><%= "Editando Rotina" %></h3>
<%= render 'form' %>

app/views/admin/rules/index.html.erb
<h1>Rotinas</h1>

<% if @rules.present? %>
  <table class="table table-striped">
    <tr>
      <th>Label</th>
      <th class="span1"></th>
      <th class="span1"></th>
      <th class="span1"></th>
    </tr>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.label %></td>
        <td>
          <input type="checkbox" data-handle-width="65px" data-size="mini" data-role="flipswitch" name="switch" id="active_<%= rule.id %>">
          <script>
            $("#active_<%= rule.id %>").bootstrapSwitch('state', <%= rule.active %>);
            $('#active_<%= rule.id %>').on('switchChange.bootstrapSwitch', function (event, state) {
                $.ajax({
                  url: 'rules/active',
                  type: 'POST',
                  data: {
                    id: <%= rule.id %>
                  }
                });
            });
          </script>
        </td>
        <td><%= link_to 'Editar', edit_admin_rule_path(rule), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Remover', admin_rule_path(rule), :class => 'btn btn-danger btn-mini', :confirm => 'Tem certeza que deseja apagar esta expressão de substituição?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <div class='btn-group'>
    <%= link_to 'Nova Rotina', new_admin_rule_path, :class => 'btn btn-primary btn-new btn-small' %>
  </div>
<% else %>
  <p class="blank">Nenhuma expressão cadastrada. <%= link_to 'Definir uma nova rotina?', new_admin_rule_path %></p>
<% end %>

app/views/admin/rules/new.html.erb
<h3><%= "Nova Rotina" %></h3>
<%= render 'form' %>