config/routes.rb
Livrodaclasse::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  match 'scraps/:id/new', :to => 'scraps#new', :as => :new_scrap


  get 'entrar', :to => 'sessions#new', :as => :signin
  get 'auth/:provider/callback', :to => 'sessions#create'
  delete 'sair', :to => 'sessions#destroy', :as => :signout
  get 'cadastro', :to => 'users#new', :as => :new_user
  get 'apphome', :to => 'books#index', :as => :app_home
  get 'auth/failure', :to => redirect('/')
  get 'projects/terms_of_service', :to => 'projects#terms_of_service', :as => :terms_of_service
  match 'texts/enable_or_disable', :to => 'texts#enable_or_disable', :as => :enable_or_disable
  root :to => 'pages#home'
  get 'manual', :to => 'pages#manual'

  match 'contact' => 'pages#contact', :via => :post

  resources :users do
    collection do
      get 'email'
    end
  end

  resources :sessions
  resources :password_resets
  resources :books do

    member do
      post 'rules/active', to: 'books#rule_active'
    end

    resources :texts do
      post 'cancel'
      collection do
        get 'all'
        put 'save_all'
      end

      resources :comments
      collection do
        post 'sort'
      end
    end
    resources :collaborators do
      member do
        get 'resend_invitation'
      end
    end
    resources :projects
    resources :scraps
  end
  get 'books/:id/cover_info', to: 'books#cover_info', as: :book_cover_info
  get 'books/:id/revision', to: 'books#revision', as: :book_revision
  get 'books/:id/epub_viewer', to: 'books#epub_viewer', as: :epub_viewer
  post 'books/:id/upload_text', to: 'texts#create', as: :upload_text
  match 'books/:id/update_cover_info', to: 'books#update_cover_info', as: :book_update_cover_info
  match 'books/:id/generate_cover', to: 'books#generate_cover', as: :book_generate_cover

  match 'books/:id/generate_pdf', to: 'books#generate_pdf', as: :book_generate_pdf
  match 'books/:id/ask_for_download_pdf', to: 'books#ask_for_download_pdf', as: :book_ask_for_download_pdf
  match 'books/:id/download_pdf', to: 'books#download_pdf', as: :book_download_pdf
  match 'books/:id/generate_ebook', to: 'books#generate_ebook', as: :book_generate_ebook

  match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
  match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer
  resources :scraps, :only => [:index, :create, :edit, :update, :destroy]

  namespace :admin do
    root :to => 'dashboard#index'

    match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
    match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer

    match 'users/:id/books', :to => 'users#books', :as => :users_books
    match 'users/add_book', :to => 'users#add_book', :as => :users_add_book
    match 'users/remove_book', :to => 'users#remove_book', :as => :users_remove_book

    get 'dashboard/default_cover', :to => 'dashboard#default_cover', :as => :default_cover
    match 'dashboard/update_default_cover', :to => 'dashboard#update_default_cover', :as => :update_default_cover

    match 'dashboard/revision', :to => 'dashboard#revision', :as => :revision
    match 'dashboard/manual', :to => 'dashboard#manual', :as => :manual
    post 'dashboard/manual/update', :to => 'dashboard#manual_update', :as => :manual_update

    match 'projects/refresh', :to => 'projects#refresh', :as => :projects_refresh

    match 'projects/push', :to => 'projects#push', :as => :projects_push

    resources :projects, :only => [:index, :show, :edit, :update] do
      member do
        get 'impersonate'
        get 'refresh'
        get 'push'
      end
    end
    resources :templates, :only => :index
    resources :expressions, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :book_statuses, :only => [:index, :create, :new, :edit, :update]
    resources :profiles, :only => [:index, :create, :new, :edit, :update]
    resources :permissions, :only => [:index, :edit, :update]
    resources :publishers, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :scraps, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :users, :only => [:index, :edit, :update, :new, :create]
    resources :rules, :only => [:index, :new, :create, :destroy, :edit, :update] do
      collection do
        post 'active'
      end
    end
  end
  get '/:locale' => 'pages#home'
end

app/views/publish/content-steps/_colaborators.html.erb



<!-- STEP: 04_COLABORATORS -->
<div id="step-colaborators" class="clearfix">


	<!-- content -->
	<section class="content" style="float:none;">

		<!-- tab-book-colaborators -->
		<div class="tab-book-colaborators">
			<div class="header clearfix">
				<h2 class="sans-light ts-28 tc-blue lh-big left">Colaboradores</h2>
			</div>


			<div class="colaborators">
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big"></label>
					<input name="book[title]" type="text" value="">
				</div>

				<div class="acions">
					<a href="#" class="btn btn-default bc-blue tc-white">Procurar</a>
				</div>
			</div>


		</div>

	</section>


</div>


<script>
	
	$(document).ready(function()
	{
		// common.bridge('post', 'http://192.168.0.114:3000/books/a754ac62-c442-5988-96d5-77429bde85a4/collaborators.json', _data, function(data){ console.log(data) });
	});

</script>

app/views/publish/content-steps/_content.html.erb



<!-- STEP: 01_CONTENT -->
<div id="step-content" class="clearfix">

	<!-- content-navigation -->
	<aside class="content-navigation">
		<nav>
			<ul>
				<li><a href="javascript:;" data-tab="tab-chapters" class="ico-chapters">Capítulos</a></li>
				<li><a href="javascript:;" data-tab="tab-send-file" class="ico-send-file">Enviar arquivo</a></li>
			</ul>
		</nav>
	</aside>



	<!-- content -->
	<section class="content">


		<!-- tab-chapters -->
		<div class="tab-chapters none">
			<div class="header clearfix">
				<h2 class="sans-light ts-28 tc-blue lh-big left">Capítulos</h2>
				<a rel="cleanbox" href="/books/<%= @book.uuid %>/texts/new" class="btn-default tc-white bc-blue right">Adicionar novo</a>
			</div>



			<!-- 
				TODO:
				- show loading.
				- open editor text_controller #get 
			-->



			<!-- apple list -->
			<div class="chapters">
				<div class="empty none">
					Nenhum capítulo cadastrado.
				</div>

				<div role="template" class="item flex-center">
					<div class="ico-drag">
						<a href="#"></a>
					</div>
					<div class="chapter-name">
						<a rel="cleanbox" data-onclose="top.$('.cleanbox').eq(0).find('iframe')[0].contentWindow.publish_wizard.fillChapters();" href="/books/{book_id}/texts/{chapter_id}" class="sans-regular ts-18 tc-black">{title}</a>
					</div>
					<div class="time">
						<!-- <p class="sans-light ts-16 tc-gray-light ta-right">{time_ago}</p> -->
					</div>
				</div>

				<div class="receiver"></div>
			</div>

		</div>



		<!-- tab-send-file -->
		<div class="tab-send-file none">
			<form method="post" action="">
				<div class="header clearfix">
					<h2 class="sans-light ts-28 tc-blue">Enviar arquivo</h2>
				</div>

				<div class="select-file clearfix">
					<div class="ico left">
						<img src="/assets/publish/ico-send-file.png" alt="" />
					</div>
					<div class="info left">
						<p class="sans-regular ts-18 gray-dark lh-default">
							O arquivo deve ser do formato: <br/>DOC, DOCX ou TXT.
						</p>
						<button class="btn-default tc-white bc-blue">Selecionar arquivo</button>
					</div>
				</div>

				<div class="sending-file clearfix none">
					<div class="clean-progress green"><i style="width:60%;"></i></div>
					<p class="sans-regular ts-18 gray-dark left">Enviando arquivo: MeuLivro.doc...</p>
					<a href="#" class="sans-regular ts-16 tc-blue right">Cancelar</a>
					<p class="sans-semibold ts-18 tc-green right">Enviado!</p>
				</div>

				<div class="building-book clearfix none">
					<div class="clean-progress blue"><i style="width:30%;"></i></div>
					<p class="sans-regular ts-18 gray-dark left">Criando livro...</p>
					<p class="sans-semibold ts-18 tc-blue right">2 capítulos adicionados.</p>
				</div>
			</form>



			<!-- TODO: add upload form. -->


			
		</div>


	</section>

</div>

app/views/publish/content-steps/_download.html.erb



<!-- STEP: 05_DOWNLOAD -->
<div id="step-download" class="clearfix">

	<!-- content -->
	<section class="content" style="float:none;">

		<!-- tab-output -->
		<div class="tab-output">
			<div class="header clearfix">
				<h2 class="sans-light ts-28 tc-blue lh-big left">Salvar</h2>
			</div>

			<!-- <p class="sans-regular ts-18 tc-gray-dark lh-default">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
			<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique minus quidem maxime eum quasi numquam culpa tempore dicta rerum ab. Pariatur, quos libero, voluptas dolorem temporibus iure atque cupiditate id.</p> -->
			
			<%= render 'books/book_info' if (controller_name == 'books' and params[:id]) || params[:book_id] %>
		</div>

	</section>

</div>



<!-- JS -->
<script type="text/javascript">
	var bookurl = '<%= book_generate_pdf_path(@book.uuid) %>';
	var ebookurl = '<%= book_generate_ebook_path(@book.uuid) %>';
	var ask_for_download_pdf_url = '<%= book_ask_for_download_pdf_path(@book.uuid) %>';

	function getByType(type){
		if (type == "pdf"){
			return {
				url : bookurl,
				title: "<%= t(:pdf_progress_title) %>",
				download: "<%= t(:pdf_generation_download) %>",
				error: "<%= t(:pdf_generation_error) %>"
			};
		} else if (type == "ebook"){
			return {
				url : ebookurl,
				title: "<%= t(:ebook_progress_title) %>",
				download: "<%= t(:ebook_generation_download) %>",
				error: "<%= t(:ebook_generation_error) %>"
			};
		} else {
			return {
				url : ebookurl + "?kindle=true",
				title: "<%= t(:kindle_progress_title) %>",
				download: "<%= t(:kindle_generation_download) %>",
				error: "<%= t(:kindle_generation_error) %>"
			};
		}
	}

	function generate(type){
		var o = getByType(type);
		$.ajax({
			url: o.url,
			dataType: 'json',
			beforeSend: function () {
				$(".progress-modal").fancybox({
					helpers : {
							overlay : {
									locked : true,
									closeClick : false
							},
							title: {
								type: 'inside',
								position: 'bottom'
							}
					},
					title: o.title,
					autoSize: true,
					minHeight: 10,
					closeBtn: true,
					autoCenter: true
				}).trigger('click')
			},
			context: document.body
		}).done(function(response) {
			if (response.result == "success") {
				parent.jQuery.fancybox.close();
				window.location = response.path;
			} else {
				var link = $(document.createElement('a')).attr('href',response.path).text('<%= t(:click_here) %>');
				$('img.progress-modal').hide();
				$('div.fancybox-title').text(o.download).append(link);
				$('div.fancybox-title').html();
			}
		}).fail(function(response) {
			alert(o.error);
		});
	}

	$("#generate-pdf").on("click", function (){
		generate("pdf");
	});

	$("#generate-ebook").on("click", function (){
		generate("ebook");
	});

	$("#generate-kindle").on("click", function (){
		generate("kindle");
	});
</script>

app/views/publish/content-steps/_metadata.html.erb



<!-- STEP: 03_METADATA -->
<div id="step-metadata" class="clearfix">

	<!-- content-navigation -->
	<aside class="content-navigation">
		<nav>
			<ul>
				<li><a href="#" data-tab="tab-book-info" class="ico-book-info">Dados do livro</a></li>
				<li><a href="#" data-tab="tab-book-ficha-catalografica" class="ico-book-ficha-catalografica">Ficha catalográfica</a></li>
				<li><a href="#" data-tab="tab-book-instituicao" class="ico-shop-local">Instituição</a></li>
			</ul>
		</nav>
	</aside>



	<!-- content -->
	<section class="content">


		<!-- tab-book-info -->
		<div class="tab-book-info none">
			<form id="book-info-form" method="put" action="/books/<%= @book.uuid %>.json">
				<div class="header clearfix">
					<h2 class="sans-light ts-28 tc-blue lh-big left">Dados do livro</h2>
				</div>

				<!-- inputs -->
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big">Título do livro</label>
					<input name="book[title]" type="text" value="<%= @book.title %>" />
				</div>
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big">Subtítulo</label>
					<input name="book[book_data][subtit]" type="text" value="<%= @book.book_data.subtit %>" />
				</div>
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big">Autor</label>
					<input name="book[book_data][autor]" type="text" value="<%= @book.book_data.autor %>" />
				</div>
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big">Organizador</label>
					<input name="book[book_data][organizador]" type="text" value="<%= @book.book_data.organizador %>" />
				</div>
				<div class="form-item flex-top">
					<label class="ts-18 tc-gray-light lh-big">Prefácio</label>
					<input name="book[book_data][introdutor]" type="text" value="<%= @book.book_data.introdutor %>" />
				</div>
				
				<!-- buttons -->
				<div class="buttons">
					<button class="btn-default bc-blue tc-white">Salvar</button>
				</div>
			</form>
		</div>



		<!-- tab-book-ficha-catalografica -->
		<div class="tab-book-ficha-catalografica none">
			<form id="book-ficha-catalografica-form" method="post" action="/output-example">
				<div class="header clearfix">
					<h2 class="sans-light ts-28 tc-blue">Ficha catalográfica</h2>
				</div>

				<%= simple_form_for(@book, :html => {:class => 'form-vertical', :multipart => true}) do |b| %>
					<%= b.simple_fields_for @book.book_data do |f| %>
						<%= render :partial => '/book_datas/cataloging', :locals => {:f => f, :b => b} %>

						<%= b.button :submit, @book.new_record? ? t('book_create') : t('book_update'), class: 'btn-success' %>
					<% end %>
				<% end %>

			</form>
		</div>



		<!-- tab-book-instituicao -->
		<div class="tab-book-instituicao none">
			<form action="">
				<div class="header clearfix">
					<h2 class="sans-light ts-28 tc-blue">Instituição</h2>
				</div>

				<%= simple_form_for(@book, :html => {:class => 'form-vertical', :multipart => true}) do |b| %>
					<%= b.simple_fields_for @book.book_data do |f| %>
						<%= render :partial => '/book_datas/partners', :locals => {:f => f, :b => b} %>
						
						<%= b.button :submit, @book.new_record? ? t('book_create') : t('book_update'), class: 'btn-success' %>
					<% end %>
				<% end %>
			</form>
		</div>


	</section>

</div>