config/routes.rb
Livrodaclasse::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  match 'scraps/:id/new', :to => 'scraps#new', :as => :new_scrap


  get 'entrar', :to => 'sessions#new', :as => :signin
  get 'auth/:provider/callback', :to => 'sessions#create'
  delete 'sair', :to => 'sessions#destroy', :as => :signout
  get 'cadastro', :to => 'users#new', :as => :new_user
  get 'apphome', :to => 'books#index', :as => :app_home
  get 'auth/failure', :to => redirect('/')
  get 'projects/terms_of_service', :to => 'projects#terms_of_service', :as => :terms_of_service
  match 'texts/enable_or_disable', :to => 'texts#enable_or_disable', :as => :enable_or_disable
  root :to => 'pages#home'
  get 'manual', :to => 'pages#manual'

  match 'contact' => 'pages#contact', :via => :post

  resources :users do
    collection do
      get 'email'
    end
  end

  resources :sessions
  resources :password_resets
  resources :books do

    member do
      post 'rules/active', to: 'books#rule_active'
    end

    resources :texts do
      post 'cancel'
      collection do
        get 'all'
        put 'save_all'
      end

      resources :comments
      collection do
        post 'sort'
      end
    end
    resources :collaborators do
      member do
        get 'resend_invitation'
      end
    end
    resources :projects
    resources :scraps
  end
  get 'books/:id/cover_info', to: 'books#cover_info', as: :book_cover_info
  get 'books/:id/revision', to: 'books#revision', as: :book_revision
  get 'books/:id/epub_viewer', to: 'books#epub_viewer', as: :epub_viewer
  post 'books/:id/upload_text', to: 'texts#create', as: :upload_text
  match 'books/:id/update_cover_info', to: 'books#update_cover_info', as: :book_update_cover_info
  match 'books/:id/generate_cover', to: 'books#generate_cover', as: :book_generate_cover

  match 'books/:id/generate_pdf', to: 'books#generate_pdf', as: :book_generate_pdf
  match 'books/:id/ask_for_download_pdf', to: 'books#ask_for_download_pdf', as: :book_ask_for_download_pdf
  match 'books/:id/download_pdf', to: 'books#download_pdf', as: :book_download_pdf
  match 'books/:id/generate_ebook', to: 'books#generate_ebook', as: :book_generate_ebook

  match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
  match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer
  resources :scraps, :only => [:index, :create, :edit, :update, :destroy]

  namespace :admin do
    root :to => 'dashboard#index'

    match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
    match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer

    match 'users/:id/books', :to => 'users#books', :as => :users_books
    match 'users/add_book', :to => 'users#add_book', :as => :users_add_book
    match 'users/remove_book', :to => 'users#remove_book', :as => :users_remove_book

    get 'dashboard/default_cover', :to => 'dashboard#default_cover', :as => :default_cover
    match 'dashboard/update_default_cover', :to => 'dashboard#update_default_cover', :as => :update_default_cover

    match 'dashboard/revision', :to => 'dashboard#revision', :as => :revision
    match 'dashboard/manual', :to => 'dashboard#manual', :as => :manual
    post 'dashboard/manual/update', :to => 'dashboard#manual_update', :as => :manual_update

    match 'projects/refresh', :to => 'projects#refresh', :as => :projects_refresh

    match 'projects/push', :to => 'projects#push', :as => :projects_push

    resources :projects, :only => [:index, :show, :edit, :update] do
      member do
        get 'impersonate'
        get 'refresh'
        get 'push'
      end
    end
    resources :templates, :only => :index
    resources :expressions, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :book_statuses, :only => [:index, :create, :new, :edit, :update]
    resources :profiles, :only => [:index, :create, :new, :edit, :update]
    resources :permissions, :only => [:index, :edit, :update]
    resources :publishers, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :scraps, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :users, :only => [:index, :edit, :update, :new, :create]
    resources :rules, :only => [:index, :new, :create, :destroy, :edit, :update] do
      collection do
        post 'active'
      end
    end
  end
  get '/:locale' => 'pages#home'
end

app/models/publisher.rb
# encoding: UTF-8

class Publisher < ActiveRecord::Base

  attr_accessible               :name, :url, :logo, :logo_alternative, :official_name, :address, :district, :city, :uf, :telephone, :trello_email, :text_email

  has_attached_file :logo,
                    :styles => {
                      :normal => ["600x600>", :png],
                      :small => ["300x300#", :png]
                    }

  has_attached_file :logo_alternative,
                    :styles => {
                      :normal => ["600x600>", :png],
                      :small => ["300x300#", :png]
                    }

  # maybe move to db:seeds later
  def self.get_default
    if Publisher.all.size == 0
    	p = Publisher.new
    	p.name = "Editora Hedra"
    	p.url = "livrodaclasse.com.br"
    	p.official_name = "Hedra Educação Ltda."
    	p.address = "Rua Fradique Coutinho 1139 Subsolo"
    	p.district = "Vila Madalena"
    	p.city = "São Paulo"
    	p.uf = "SP"
    	p.telephone = "(11) 3097-8304"
      p.trello_email = "jorgesallum+y5qrgfspixht6l17rpuy@boards.trello.com"
      p.text_email = "Caro @name,\n\nSeu livro cadastrado em nosso sistema de aprovação teve seu status alterado para: @status\n\n        Para entrar em contato com nossos editores, utilize o mural presente no site http://livrodaclasse.com.br\n\nEditora Hedra"
    	p.save
    end
  	Publisher.first
  end

  def self.get_current request_host
    publisher = Publisher.where("url LIKE ?", "%#{request_host}%").first
    if publisher.nil?
      Publisher.get_default
    else
      publisher
    end
  end

  def self.get_current_app
    "#{CONFIG[Rails.env.to_sym]["app_name"]}"
  end

end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < Admin::ApplicationController

  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(params[:publisher])
    if @publisher.save
      redirect_to admin_publishers_path, :notice => "Uma nova editora foi definida."
    else
      render :new
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update_attributes(params[:publisher])
    if @publisher.save
      redirect_to admin_publishers_path, :notice => "Editora atualizada."
    else
      render :edit
    end
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    redirect_to admin_publishers_path, :notice => "Editora removida com sucesso."
  end
end

app/views/admin/publishers/_form.html.erb
<%= simple_form_for([:admin, @publisher], :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :official_name %>
    <%= f.input :url %>
    <%= f.input :trello_email %>
    <%= f.input :logo %>
    <%= f.input :logo_alternative %>
    <%= f.input :address %>
    <%= f.input :district %>
    <%= f.input :city %>
    <%= f.input :uf %>
    <%= f.input :telephone %>
    <%= f.input :text_email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/publishers/edit.html.erb
<h3><%= "Editando Editora" %></h3>
<%= render 'form' %>

app/views/admin/publishers/index.html.erb
<h1>Expressões</h1>

<% if @publishers.present? %>
  <table class="table table-striped">
    <tr>
      <th>Editora</th>
      <th>URL</th>
      <th></th>
      <th></th>
    </tr>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= publisher.url %></td>
        <td><%= link_to 'Editar', edit_admin_publisher_path(publisher), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Remover', admin_publisher_path(publisher), :class => 'btn btn-danger btn-mini', :confirm => 'Tem certeza que deseja apagar esta editora?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <div class="btn-group">
    <%= link_to 'Nova Editora', new_admin_publisher_path, :class => 'btn btn-primary btn-new btn-small' %>
  </div>
<% else %>
  <p class="blank">Nenhuma editora cadastrada. <%= link_to 'Definir uma nova editora?', new_admin_publisher_path %></p>
<% end %>

app/views/admin/publishers/new.html.erb
<h3><%= "Nova Editora" %></h3>
<%= render 'form' %>