config/routes.rb
Livrodaclasse::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  match 'scraps/:id/new', :to => 'scraps#new', :as => :new_scrap


  get 'entrar', :to => 'sessions#new', :as => :signin
  get 'auth/:provider/callback', :to => 'sessions#create'
  delete 'sair', :to => 'sessions#destroy', :as => :signout
  get 'cadastro', :to => 'users#new', :as => :new_user
  get 'apphome', :to => 'books#index', :as => :app_home
  get 'auth/failure', :to => redirect('/')
  get 'projects/terms_of_service', :to => 'projects#terms_of_service', :as => :terms_of_service
  match 'texts/enable_or_disable', :to => 'texts#enable_or_disable', :as => :enable_or_disable
  root :to => 'pages#home'
  get 'manual', :to => 'pages#manual'

  match 'contact' => 'pages#contact', :via => :post

  resources :users do
    collection do
      get 'email'
    end
  end

  resources :sessions
  resources :password_resets
  resources :books do

    member do
      post 'rules/active', to: 'books#rule_active'
    end

    resources :texts do
      post 'cancel'
      collection do
        get 'all'
        put 'save_all'
      end

      resources :comments
      collection do
        post 'sort'
      end
    end
    resources :collaborators do
      member do
        get 'resend_invitation'
      end
    end
    resources :projects
    resources :scraps
  end
  get 'books/:id/cover_info', to: 'books#cover_info', as: :book_cover_info
  get 'books/:id/revision', to: 'books#revision', as: :book_revision
  get 'books/:id/epub_viewer', to: 'books#epub_viewer', as: :epub_viewer
  post 'books/:id/upload_text', to: 'texts#create', as: :upload_text
  match 'books/:id/update_cover_info', to: 'books#update_cover_info', as: :book_update_cover_info
  match 'books/:id/generate_cover', to: 'books#generate_cover', as: :book_generate_cover

  match 'books/:id/generate_pdf', to: 'books#generate_pdf', as: :book_generate_pdf
  match 'books/:id/ask_for_download_pdf', to: 'books#ask_for_download_pdf', as: :book_ask_for_download_pdf
  match 'books/:id/download_pdf', to: 'books#download_pdf', as: :book_download_pdf
  match 'books/:id/generate_ebook', to: 'books#generate_ebook', as: :book_generate_ebook

  match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
  match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer
  resources :scraps, :only => [:index, :create, :edit, :update, :destroy]

  namespace :admin do
    root :to => 'dashboard#index'

    match 'scraps/:id/thread', :to => 'scraps#thread', :as => :scraps_thread
    match 'scraps/:id/answer', :to => 'scraps#answer', :as => :scraps_answer

    match 'users/:id/books', :to => 'users#books', :as => :users_books
    match 'users/add_book', :to => 'users#add_book', :as => :users_add_book
    match 'users/remove_book', :to => 'users#remove_book', :as => :users_remove_book

    get 'dashboard/default_cover', :to => 'dashboard#default_cover', :as => :default_cover
    match 'dashboard/update_default_cover', :to => 'dashboard#update_default_cover', :as => :update_default_cover

    match 'dashboard/revision', :to => 'dashboard#revision', :as => :revision
    match 'dashboard/manual', :to => 'dashboard#manual', :as => :manual
    post 'dashboard/manual/update', :to => 'dashboard#manual_update', :as => :manual_update

    match 'projects/refresh', :to => 'projects#refresh', :as => :projects_refresh

    match 'projects/push', :to => 'projects#push', :as => :projects_push

    resources :projects, :only => [:index, :show, :edit, :update] do
      member do
        get 'impersonate'
        get 'refresh'
        get 'push'
      end
    end
    resources :templates, :only => :index
    resources :expressions, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :book_statuses, :only => [:index, :create, :new, :edit, :update]
    resources :profiles, :only => [:index, :create, :new, :edit, :update]
    resources :permissions, :only => [:index, :edit, :update]
    resources :publishers, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :scraps, :only => [:index, :create, :new, :edit, :update, :destroy]
    resources :users, :only => [:index, :edit, :update, :new, :create]
    resources :rules, :only => [:index, :new, :create, :destroy, :edit, :update] do
      collection do
        post 'active'
      end
    end
  end
  get '/:locale' => 'pages#home'
end

app/models/scrap.rb
class Scrap < ActiveRecord::Base
  attr_accessible :book_id, :content, :is_admin, :admin_name, :parent_scrap_id, :answered

  belongs_to :book

  def childs
  	Scrap.where(:parent_scrap_id => self.id).order('created_at ASC').all
  end

end

app/controllers/admin/scraps_controller.rb
class Admin::ScrapsController < Admin::ApplicationController

  skip_before_filter :authentication_admin_check 
  before_filter :auth_admin_or_publisher 

  def index
    @scraps = Scrap.where(:parent_scrap_id => nil).order('answered, created_at DESC').all
  end

  def new
    @scrap = Scrap.new
    @books = Book.all
  end

  def create
    @scrap = Scrap.new(params[:scrap])
    @scrap.is_admin = true
    @scrap.answered = true
    @scrap.admin_name = Publisher.find(current_publisher).name
    if @scrap.save

      AdminMailer.scrap_notifier(@scrap.book, @scrap).deliver

      redirect_to admin_scraps_path, :notice => "Uma recado foi escrito."
    else
      render :new
    end
  end

  def thread
    @scrap = Scrap.find(params[:id])
    @book = @scrap.book
  end

  def answer
    parent_scrap = Scrap.find(params[:parent])

    @scrap = Scrap.new
    @scrap.parent_scrap_id = parent_scrap.id
    @scrap.content = params[:content]
    @scrap.is_admin = true
    @scrap.admin_name = 'Editora Hedra'
    @scrap.book_id = parent_scrap.book.id
    @scrap.save

    parent_scrap.answered = true
    parent_scrap.save

    AdminMailer.scrap_notifier(@scrap.book, @scrap).deliver
    
    render layout: false
  end
end

# for role publisher
# @scraps = Scrap.joins(:book).where(:parent_scrap_id => nil, 'books.organizer_id' => current_user.id).order('answered, created_at DESC').all
# @books = Book.where('organizer_id' => current_user.id)

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController

  def index
    @book = Book.find_by_uuid_or_id(params[:book_id])
    @scraps = Scrap.where(:parent_scrap_id => nil, :book_id => @book.id).order('created_at DESC').all

    if @scraps.count == 0 and can_write?
      redirect_to new_scrap_path(@book.id)
    end
  end

  def new
    @scrap = Scrap.new
    @book = Book.find(params[:id])
  end

  def show
    @scrap = Scrap.find params[:id]
    @book = Book.find(@scrap.book_id)
  end

  def create
    @scrap = Scrap.create(content: params[:scrap][:content], is_admin: false, answered: false, book_id: params[:scrap][:book_id])
    @book = Book.find(params[:scrap][:book_id])

    AdminMailer.scrap_notifier(@book, @scrap).deliver

    @book.scraps << @scrap
    redirect_to book_path(@book), :notice => "Recado criado."
  end

  def thread
    @scrap = Scrap.find(params[:id])
    @book = @scrap.book
  end

  def answer
    parent_scrap = Scrap.find(params[:parent])
    @scrap = Scrap.new
    @scrap.parent_scrap_id = parent_scrap.id
    @scrap.content = params[:content]
    @scrap.book_id = parent_scrap.book.id
    @scrap.save

    AdminMailer.scrap_notifier(parent_scrap.book, @scrap).deliver

    parent_scrap.answered = false
    parent_scrap.save
    render layout: false
  end

end

app/helpers/scrap_helper.rb
module ScrapHelper
end

app/views/admin/scraps/answer.html.erb
<div class="scrap-child">
    <span><%= @scrap.is_admin? ? @scrap.admin_name : @scrap.book.organizer.name %></span>
    <span class="label label-warning"><%= @scrap.created_at.strftime("%d/%m/%Y") %></span>
    <div class="scrap-content"><span><%= @scrap.content %></span></div>
</div>

app/views/admin/scraps/index.html.erb
<h1>Recados</h1>

<% if @scraps.present? %>
  <table class="table table-striped">
    <tr>
      <th></th>
      <th></th>
      <th>Data</th>
      <th>Livro</th>
      <th>Conversa</th>
      <th></th>
    </tr>
    <% @scraps.each do |scrap| %>
      <tr>
        <td><span class="badge"><%= scrap.answered? ? '' : '!' %></span></td>
        <td><%= "##{scrap.id}" %></td>
        <td><span class="label label-info"><%= scrap.created_at.strftime("%d/%m/%Y") %></span></td>
        <td><%= link_to scrap.book.title, book_path(scrap.book.uuid) %></td>
        <td><%= "#{scrap.content[0..20]}..." %></td>
        <td><%= link_to 'Expandir', admin_scraps_thread_path(scrap), :class => 'btn btn-mini' %></td>
      </tr>
    <% end %>
  </table>
  <div class="btn-group">
    <%= link_to 'Novo Recado', new_admin_scrap_path, :class => 'btn btn-primary btn-new btn-small' %>
  </div>
<% else %>
  <p class="blank">Nenhum recado cadastrada. <%= link_to 'Definir um novo recado?', new_admin_scrap_path %></p>
<% end %>

app/views/admin/scraps/new.html.erb
<h3><%= "Nova Conversa" %></h3>

<%= simple_form_for([:admin, @scrap], :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :book_id, :collection => @books, :include_blank => false %>
    <%= f.input :content, :as => :text, :label => 'Conteúdo' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/scraps/thread.html.erb
<script>
  function adminAnswer(id){
    var contentValue = $("#answer-content-"+id).val();
    if (contentValue.length > 0){
      $.post("answer", { parent: id, content: contentValue }, function( data ) {
        $("#scrap-childs").append(data);
      }, 'html');
      $("#answer-content-"+id).val('');
    }
  }
</script>

<div class="row">
  <div class="span9">
    <h1>Recados - <%= @book.title %></h1>
  </div>
</div>
<div class="scrap-parent">
  <span class="badge"><%= @scrap.answered? ? '' : '!' %></span>
  <span><%= @scrap.is_admin? ? @scrap.admin_name : @book.organizer.name %></span>
  <span class="label label-info"><%= @scrap.created_at.strftime("%d/%m/%Y") %></span>
  <div class="scrap-content"><span><%= @scrap.content %></span></div>
</div>
<div id="scrap-childs">
  <% @scrap.childs.each do |child| %>
    <div class="scrap-child">
      <span><%= child.is_admin? ? child.admin_name : @book.organizer.name %></span>
      <span class="label label-warning"><%= child.created_at.strftime("%d/%m/%Y") %></span>
      <div class="scrap-content"><span><%= child.content %></span></div>
    </div>
  <% end %>
</div>
<div class="scrap-answer">
  <textarea id=<%= "answer-content-#{@scrap.id}" %> rows="2" cols="30"></textarea>
  <button type="button" class="btn btn-primary" onclick="adminAnswer(<%= @scrap.id %>);">Responder</button>
</div>